name: Build Windows EXE

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r mini-downsub-replit/requirements.txt
          pip install pyinstaller

      - name: Build EXE (one-folder)
        working-directory: mini-downsub-replit
        run: |
          pyinstaller --noconfirm --name mini-downsub --add-data "templates;templates" main.py

      - name: Zip portable folder
        run: |
          powershell -Command "Compress-Archive -Path mini-downsub-replit\\dist\\mini-downsub\\* -DestinationPath mini-downsub-windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mini-downsub-windows
          path: mini-downsub-windows.zip
